
import 'package:cloud_firestore/cloud_firestore.dart';

class TalentModel{
  final String userId,firstName,lastName,email,profilePicture,gender,county,state,city,postalCode,drivingLicense,
      idCard,passport,otherId,country,hairColor,eyeColor,buildType,scarPicture,
      tattooPicture;
  Timestamp dateOfBirth;
  num heightCm,heightFeet,waistCm,waistInches,weightKg,weightPound,wearSizeCm,wearSizeInches,chestCm,chestInches,hipCm,hipInches,inseamCm,inseamInches,
      shoesCm,shoesInches,age;
  bool isDrivingLicense,isIdCard,isPassport,isOtherId,isScar,isTattoo;
  List languages,sports,hobbies,talent,portfolioImageLink,portfolioVideoLink,polaroidImageLink;


  TalentModel.name(
      this.userId,
      this.firstName,
      this.lastName,
      this.email,
      this.profilePicture,
      this.gender,
      this.county,
      this.state,
      this.city,
      this.postalCode,
      this.drivingLicense,
      this.idCard,
      this.passport,
      this.otherId,
      this.country,
      this.hairColor,
      this.eyeColor,
      this.buildType,
      this.scarPicture,
      this.tattooPicture,
      this.dateOfBirth,
      this.heightCm,
      this.heightFeet,
      this.waistCm,
      this.waistInches,
      this.weightKg,
      this.weightPound,
      this.wearSizeCm,
      this.wearSizeInches,
      this.chestCm,
      this.chestInches,
      this.hipCm,
      this.hipInches,
      this.inseamCm,
      this.inseamInches,
      this.shoesCm,
      this.shoesInches,
      this.age,
      this.isDrivingLicense,
      this.isIdCard,
      this.isPassport,
      this.isOtherId,
      this.isScar,
      this.isTattoo,
      this.languages,
      this.sports,
      this.hobbies,
      this.talent,
      this.portfolioImageLink,
      this.portfolioVideoLink,
      this.polaroidImageLink,);

  Map<String, dynamic> toMap() {
    return {
      'userId': userId,
      'firstName': firstName,
      'lastName': lastName,
      'email': email,
      'profilePicture': profilePicture,
      'gender': gender,
      'county': county,
      'state': state,
      'city': city,
      'postalCode': postalCode,
      'drivingLicense': drivingLicense,
      'idCard': idCard,
      'passport': passport,
      'otherId': otherId,
      'country': country,
      'hairColor': hairColor,
      'eyeColor': eyeColor,
      'buildType': buildType,
      'scarPicture': scarPicture,
      'tattooPicture': tattooPicture,
      'dateOfBirth': dateOfBirth,
      'heightCm': heightCm,
      'heightFeet': heightFeet,
      'waistCm': waistCm,
      'waistInches': waistInches,
      'weightKg': weightKg,
      'weightPound': weightPound,
      'wearSizeCm': wearSizeCm,
      'wearSizeInches': wearSizeInches,
      'chestCm': chestCm,
      'chestInches': chestInches,
      'hipCm': hipCm,
      'hipInches': hipInches,
      'inseamCm': inseamCm,
      'inseamInches': inseamInches,
      'shoesCm': shoesCm,
      'shoesInches': shoesInches,
      'age': age,
      'isDrivingLicense': isDrivingLicense,
      'isIdCard': isIdCard,
      'isPassport': isPassport,
      'isOtherId': isOtherId,
      'isScar': isScar,
      'isTattoo': isTattoo,
      'languages': languages,
      'sports': sports,
      'hobbies': hobbies,
      'talent': talent,
      'portfolioImageLink': portfolioImageLink,
      'portfolioVideoLink': portfolioVideoLink,
      'polaroidImageLink': polaroidImageLink
    };
  }

  factory TalentModel.fromMap(Map<String, dynamic> map) {
    return TalentModel.name(
      map['userId'] as String,
      map['firstName'] as String,
      map['lastName'] as String,
      map['email'] as String,
      map['profilePicture'] as String,
      map['gender'] as String,
      map['county'] as String,
      map['state'] as String,
      map['city'] as String,
      map['postalCode'] as String,
      map['drivingLicense'] as String,
      map['idCard'] as String,
      map['passport'] as String,
      map['otherId'] as String,
      map['country'] as String,
      map['hairColor'] as String,
      map['eyeColor'] as String,
      map['buildType'] as String,
      map['scarPicture'] as String,
      map['tattooPicture'] as String,
      map['dateOfBirth'] as Timestamp,
      map['heightCm'] as num,
      map['heightFeet'] as num,
      map['waistCm'] as num,
      map['waistInches'] as num,
      map['weightKg'] as num,
      map['weightPound'] as num,
      map['wearSizeCm'] as num,
      map['wearSizeInches'] as num,
      map['chestCm'] as num,
      map['chestInches'] as num,
      map['hipCm'] as num,
      map['hipInches'] as num,
      map['inseamCm'] as num,
      map['inseamInches'] as num,
      map['shoesCm'] as num,
      map['shoesInches'] as num,
      map['age'] as num,
      map['isDrivingLicense'] as bool,
      map['isIdCard'] as bool,
      map['isPassport'] as bool,
      map['isOtherId'] as bool,
      map['isScar'] as bool,
      map['isTattoo'] as bool,
      map['languages'] as List,
      map['sports'] as List,
      map['hobbies'] as List,
      map['talent'] as List,
      map['portfolioImageLink'] as List,
      map['portfolioVideoLink'] as List,
      map['polaroidImageLink'] as List,

    );
  }
}